# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Grh4dB9N7Me2hG931f9cPpmnU-gbCF70
"""

def dfs(start, goal, max_depth=9):
    stack = [(start, [start])]
    visited = set()

    while stack:
        state, path = stack.pop()

        if state == goal:
            return path

        if len(path) - 1 >= max_depth:
            continue

        visited.add(state)

        zero = state.index(0)
        row, col = divmod(zero, 3)

        # Right, Down, Left, Up
        moves = [(0, 1), (1, 0), (0, -1), (-1, 0)]

        for dr, dc in moves:
            nr, nc = row + dr, col + dc

            if 0 <= nr < 3 and 0 <= nc < 3:
                new_state = list(state)
                new_zero = nr * 3 + nc

                new_state[zero], new_state[new_zero] = \
                    new_state[new_zero], new_state[zero]

                new_state = tuple(new_state)

                if new_state not in visited:
                    stack.append((new_state, path + [new_state]))

    return None


start = (2, 3, 0,
         1, 5, 6,
         4, 7, 8)

goal = (1, 2, 3,
        4, 5, 6,
        7, 8, 0)

solution = dfs(start, goal, 9)

if solution:
    print("DFS Solution")
    print("------------")

    for i, state in enumerate(solution):
        print("Step", i)
        print(state[0], state[1], state[2])
        print(state[3], state[4], state[5])
        print(state[6], state[7], state[8])
        print()

    print("Total Steps:", len(solution))
else:
    print("No solution found")

def IDS(start, goal):

    depth = 0

    while True:

        result = DLS(start, goal, depth)

        if result != None:
            return result

        depth = depth + 1


def DLS(node, goal, limit):

    if node == goal:
        return node

    if limit == 0:
        return None

    for child in get_children(node):

        result = DLS(child, goal, limit - 1)

        if result != None:
            return result

    return None

def dls(node, goal, limit, path):
    if node == goal:
        return path

    if limit == 0:
        return None

    for child in graph[node]:
        if child not in path:
            result = dls(child, goal, limit - 1, path + [child])
            if result:
                return result

    return None


def ids(start, goal):
    depth = 0

    while True:
        print("Depth Limit:", depth)

        result = dls(start, goal, depth, [start])

        if result:
            return result

        depth += 1


# Graph
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F', 'G'],
    'D': [],
    'E': ['H'],
    'F': [],
    'G': [],
    'H': []
}

start = 'A'
goal = 'H'

path = ids(start, goal)

print("\nSolution Path:", " -> ".join(path))
print("Steps:", len(path) - 1)